name: Cleanup Images

on:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Delete old images
        uses: snok/container-retention-policy@v2
        with:
          image-names: ollama2api
          cut-off: 7d
          keep-at-least: 5
